# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
        networks:
            - app-network

    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        networks:
            - app-network
     
#MySQL Service
    mysql:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
          - "3306:3306"
        volumes:
         - ./logs/mysql:/var/log/mysql
            
        environment:
          MYSQL_DATABASE: database
          MYSQL_ROOT_PASSWORD: your_mysql_root_password
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        networks:
           - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

